# Generated by Django 4.2.5 on 2023-09-24 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
