# Generated by Django 4.2.5 on 2023-09-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
